### PR TITLE
feat(events): create new page for events

### PR DESCRIPTION
**Pull request by lirantal**
Creates a new page for consolidating events for the Node.js community
Related: https://github.com/nodejs/nodejs.org/issues/2031

### CODE REVIEW

**Comment by lirantal** [comment]
Does the website markdown support tables? that would be much easier to display the events data both on the markdown as well as on the website.

**Comment by fharper** [comment]
@lirantal : not gonna happen?

**Comment by lirantal** [comment]
@fharper definitely is, silly enough I opened the PR on my own fork instead of the upstream one 🙃

**Comment by fharper** [comment]
@lirantal : OH, I didn't even see it wasn't the main repo...

**Comment by lirantal** [comment]
yeah that confusion happened to me as well! 😁

**Pull request closed without merging**
